### ISSUE TITLE
Error for SQL DELETE

### ISSUE THREAD

**Issue by SmashScharrer** [Kayoshi-dev/ProjetChargeon#34]
In the Customers CRUD, we have a a lot of party (Create, Update or Delete a Customer). We have a problem with the code for Delete a Customer.

This is the method to Delet a Customer :
`// Cette méthode permet de supprimer un Client
        public bool DeleteClient(string idSelected)
        {
            string query = "DELETE FROM client WHERE Cli_Id = @id";
            bool validate = false;

            MySqlCommand req = new MySqlCommand(query, connection);

            req.Parameters.Clear();
            req.Parameters.Add(new MySqlParameter("@id", idSelected));
            //req.ExecuteNonQuery(); -> Si je met cette ligne, cela fait l'erreur suivante : "System.InvalidOperationException : 'Connection must be valid and open.'"

            validate = true;

            return validate;
        }`

This is the Event when I execute the method (with a click on a button) :
`private void Supprimer_Client(object sender, EventArgs e)
        {
            // On récupère l'ID de la ComboBox
            string idSelected = cb_Nom.SelectedValue.ToString();

            CrudBornes deleteClient = new CrudBornes();
            bool deleteClientBool = deleteClient.DeleteClient(idSelected);

            if (deleteClientBool == true)
            {
                MessageBox.Show("Requête exécutée, client supprimé !");
            }
            else
            {
                MessageBox.Show("Erreur : Requête non exécutée !");
            }
        }`

And this is the connection to the database :
`class CrudBornes
	{
		private MySqlConnection connection;

		public CrudBornes() 
		{
			var ConnectObject = new DBConnect();
			this.connection = ConnectObject.GetConnection(); //On récupère la valeur de Connection grâce à la méthode GetConnection.
		}
...}

class DBConnect
    {
        private MySqlConnection connection;
        private string host;
        private string database;
        private string user;
        private string password;

		public DBConnect() //Constructeur
        {
            Initialize();
        }

        private void Initialize()
        {
            host = "localhost";
            database = "chargeon";
            user = "root";
            password = "";
            string infosDB = "SERVER=" + host + ";" + "DATABASE=" + database + ";"
                             + "UID=" + user + ";" + "PASSWORD=" + password + ";";

            connection = new MySqlConnection(infosDB);
        }

		//Cette méthode permet de récuperer l'objet Connection afin de pouvoir l'utiliser dans d'autres classes.
		public MySqlConnection GetConnection() 
		{
			return connection;
		}

        public bool OpenConnection()
        {
            try
            {
                connection.Open();
                //MessageBox.Show("Connexion ouverte!");
                return true;
            }
            catch(MySqlException ex)
            {
                if(ex.Number == 0) // Si le message d'erreur est 0
                {
                    MessageBox.Show("Erreur de connexion au serveur.");
                }
                else if (ex.Number == 1045) // Si le message d'erreur est 1045
                {
                    MessageBox.Show("User ou Password pour la BDD incorect.");
                }
				else { // Sinon on affiche un message général
					MessageBox.Show("Impossible de se connecter à la base de donnée.");	
				} 
				// et on ferme l'application
				Environment.Exit(0);
				
				// On retourne quand même false car Csharp exige une valeur de retour
				return false;
            }
        }

        public bool CloseConnection()
        {
            try
            {
                connection.Close();
                return true;
            }
            catch (MySqlException ex)
            {
                MessageBox.Show(ex.Message);
                return false;
            }
        }
...}`

**Comment by Kayoshi-dev** [comment]
Il semblerait qu'il y avait un problème lors de l’exécution de la fonction ExecuteNonQuery().

Après plusieurs recherches il faut ouvrir la connexion lors de l’exécution de cette méthode, cependant il semblerait que cela ne soit pas obligatoire pour un MySqlCommand ou même un MySqlDataAdapter, je ne sais pas vraiment pourquoi.

Donc **avant** de faire un ExecuteNonQuery(); on fera : 

connection.Open();

ExecuteNonQuery();

connection.Close();

![image](https://user-images.githubusercontent.com/28494879/56779712-8ac2d080-67dc-11e9-9d56-30ff37919fe6.png)
