### ISSUE TITLE
Error Insert Request in Client CRUD

### ISSUE THREAD

**Issue by SmashScharrer** [Kayoshi-dev/ProjetChargeon#35]
I have a problem when I execute my Insert Request. I have this error message : "System.InvalidOperationException : 'Connection must be valid and open.", at ligne 177 and 196 on CrudBorne.cs

**Comment by Kayoshi-dev** [comment]
Répondu ici :
https://github.com/Kayoshi-dev/ProjetChargeon/issues/34

Bon réflexe d'ouvrir un ticket 👍
