### ISSUE TITLE
when using stats modules, it crash

### ISSUE THREAD

**Issue by droumanet** [Kayoshi-dev/ProjetChargeon#51]
I've tried to display statistics but I fall on a bug.
![bug_jaume_stat](https://user-images.githubusercontent.com/24438463/58156819-4d385280-7c77-11e9-96b4-83b074ed2d0c.png)

**Comment by Kayoshi-dev** [comment]
We are aware of this error :)
Thanks for the report tho. 👍

**Comment by Kayoshi-dev** [comment]
I fixed it in the latest update of the software :)
Now, the combobox only displays bornes that have stats associated :)

![image](https://user-images.githubusercontent.com/28494879/58385872-7fd7a780-7ff7-11e9-8fe1-cb7b706c95ae.png)
